version: 2

multi-ecosystem-groups:
  all-dependencies:
    schedule:
      interval: "weekly"
      day: "friday"
      time: "17:00"
      timezone: "Etc/UTC"

updates:
  - package-ecosystem: "pip"
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: "all-dependencies"
    cooldown:
      default-days: 7
      include:
        - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: "all-dependencies"
    cooldown:
      default-days: 7
      include:
        - "*"
